"""initial schema

Revision ID: e8829a970144
Revises: 
Create Date: 2026-06-06 13:23:48.008800
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = 'e8829a970144'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector must exist before any vector column is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('meetings',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('participants', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ANALYZING', 'ANALYZED', 'FAILED', name='meeting_status'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_index(op.f('ix_meetings_user_id'), 'meetings', ['user_id'], unique=False)
    op.create_table('action_items',
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='action_item_status'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grounding_score', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_items_assignee'), 'action_items', ['assignee'], unique=False)
    op.create_index(op.f('ix_action_items_due_date'), 'action_items', ['due_date'], unique=False)
    op.create_index(op.f('ix_action_items_meeting_id'), 'action_items', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_action_items_status'), 'action_items', ['status'], unique=False)
    op.create_table('insights',
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('SUMMARY', 'DECISION', 'FOLLOW_UP', name='insight_type'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('grounding_score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_meeting_id'), 'insights', ['meeting_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'ordinal', name='uq_segment_ordinal')
    )
    op.create_index(op.f('ix_transcript_segments_meeting_id'), 'transcript_segments', ['meeting_id'], unique=False)
    op.create_table('citations',
    sa.Column('transcript_segment_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('insight_id', sa.String(), nullable=True),
    sa.Column('action_item_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['action_item_id'], ['action_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_segment_id'], ['transcript_segments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_action_item_id'), 'citations', ['action_item_id'], unique=False)
    op.create_index(op.f('ix_citations_insight_id'), 'citations', ['insight_id'], unique=False)
    op.create_table('reminder_logs',
    sa.Column('action_item_id', sa.String(), nullable=False),
    sa.Column('channel', sa.Enum('TELEGRAM', 'DISCORD', name='reminder_channel'), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'FAILED', name='reminder_status'), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['action_item_id'], ['action_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_logs_action_item_id'), 'reminder_logs', ['action_item_id'], unique=False)
    op.create_index(op.f('ix_reminder_logs_sent_at'), 'reminder_logs', ['sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminder_logs_sent_at'), table_name='reminder_logs')
    op.drop_index(op.f('ix_reminder_logs_action_item_id'), table_name='reminder_logs')
    op.drop_table('reminder_logs')
    op.drop_index(op.f('ix_citations_insight_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_action_item_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_transcript_segments_meeting_id'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_insights_meeting_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_action_items_status'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_meeting_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_due_date'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_assignee'), table_name='action_items')
    op.drop_table('action_items')
    op.drop_index(op.f('ix_meetings_user_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
